name: Deploy React App
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run callFunction
        run: node callFunction.js
      - name: Is done?
        run: echo Done!!!
  # test-app:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get repo code
  #       uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run callFunction
  #       run: node callFunction.js
