name: Print Pull request context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4
        with:
          name: build-files
      - name: Print build-files
        run: |
          echo "Contents of build-files artifact:"
          ls -l
