name: Print Pull request context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4
        with:
          name: build-files
      - name: Print build-files
        run: |
          echo "Contents of build-files artifact:"
          ls -l
      - name: Send to OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install openai
          python upload_to_openai.py
        shell: /usr/bin/bash -e {0}

      # - name: Send to OpenAI
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: |
      #     pip install openai
      #     openai.api_key = "$OPENAI_API_KEY"
      #     build_dir="build"
      #     for file in $build_dir/*; do
      #       if [ -f "$file" ]; then
      #         openai.File.create(
      #           file=open("$file", "rb"),
      #           purpose="code_review"
      #         )
      #         echo "Uploaded file: $file"
      #       fi
      #     done
# openai.File.create(
#   file=open("build/index.html", "rb"),
#   purpose="code_review"
# )
