name: Print Pull request context
# on: [workflow_dispatch, pull_request]
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  print:
    runs-on: ubuntu-latest
    # needs: lint
    steps:
      - name: Print context
        run: echo '${{ toJSON(github.event) }}'
