name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Print github
        run: echo 111
# ------------------------------------------

# name: WF2
# on:
#   pull_request:
#     types: [opened, edited, reopened, synchronize]
#     branches:
#       - main
# jobs:
#   code-review:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get repo code
#         uses: actions/checkout@v3
#       - name: Install dependencies
#         run: npm ci
#       - name: Build app
#         run: npm run build
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v4
#         with:
#           path: build
#           name: build-files
#       - name: Download Artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: build-files
#       - name: 'Print build-files artifact:'
#         run: |
#           echo "Contents of build-files artifact:"
#           ls -l
#       - name: Print github
#         run: |
#           echo github.event.pull_request:
#           echo '${{ toJSON(github.event.pull_request) }}'

# ------------------------------------------

# echo '${{ toJSON(github.event.pull_request) }}'

# - name: Send build-files to GPT for Review
#   run: node codeReviewHandler.js
#   env:
#     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
