name: WF2
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Print Lint Done!
        run: |
          echo Lint
          echo Done!
      # - name: Get repo code
      #   uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: npm ci
      # - name: Lint code
      #   run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Build Done!
        run: |
          echo Build
          echo Done!
      # - name: Get repo code
      #   uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build app
      #   run: npm run build
  code-review:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run codeReviewHandler
        run: node codeReviewHandler.js
